BPM:
  X:
    unit: mm
    read_only: true
    variable_class: ScalarVariable
    default_value: NULL
  Y:
    unit: mm
    read_only: true
    variable_class: ScalarVariable 

Quadrupole:
  BCTRL:
    unit: kG
    read_only: false
    variable_class: ScalarVariable
  BACT:
    unit: kG
    read_only: true
    variable_class: ScalarVariable
  BDES:
    unit: kG
    read_only: true
    variable_class: ScalarVariable
  BMIN:
    unit: kG
    read_only: true
    variable_class: ScalarVariable
  BMAX:
    unit: kG
    read_only: true
    variable_class: ScalarVariable

Solenoid:
  BCTRL:
    unit: kG-m
    read_only: false
    variable_class: ScalarVariable
  BACT:
    unit: kG-m
    read_only: true
    variable_class: ScalarVariable
  BDES:
    unit: kG-m
    read_only: true
    variable_class: ScalarVariable
  BMIN:
    unit: kG-m
    read_only: true
    variable_class: ScalarVariable
  BMAX:
    unit: kG-m
    read_only: true
    variable_class: ScalarVariable

HorizontalCorrector:
  BCTRL:
    unit: kG-m
    read_only: false
    variable_class: ScalarVariable
  BACT:
    unit: kG-m
    read_only: true
    variable_class: ScalarVariable
  BDES:
    unit: kG-m
    read_only: true
    variable_class: ScalarVariable
  BMIN:
    unit: kG-m
    read_only: true
    variable_class: ScalarVariable
  BMAX:
    unit: kG-m
    read_only: true
    variable_class: ScalarVariable

VerticalCorrector:
  BCTRL:
    unit: kG-m
    read_only: false
    variable_class: ScalarVariable
  BACT:
    unit: kG-m
    read_only: true
    variable_class: ScalarVariable
  BDES:
    unit: kG-m
    read_only: true
    variable_class: ScalarVariable
  BMIN:
    unit: kG-m
    read_only: true
    variable_class: ScalarVariable
  BMAX:
    unit: kG-m
    read_only: true
    variable_class: ScalarVariable

Screen:
  Image:ArrayData:
    unit: pixel
    read_only: true
    variable_class: NDVariable
    shape: NULL
  PNEUMATIC:
    unit: bool
    read_only: false
    variable_class: ScalarVariable
  Image:ArraySize1_RBV:
    unit: pixel
    read_only: true
    variable_class: ScalarVariable
  Image:ArraySize0_RBV:
    unit: pixel
    read_only: true
    variable_class: ScalarVariable
  RESOLUTION:
    unit: pixel/mm
    read_only: true
    variable_class: ScalarVariable

Lcavity_Overlay:
  ENLD:
    unit: MeV
    read_only: false
    variable_class: ScalarVariable
  PHAS:
    unit: Deg_S
    read_only: false
    variable_class: ScalarVariable    
  BEAMCODE1_STAT:
    unit: Boolean
    read_only: false
    variable_class: ScalarVariable    

