BPM:
  X: BPMXVariable
  Y: BPMYVariable

Quadrupole:
  BCTRL: QuadrupoleBCTRLVariable
  BCTRL.DRVL: BminVariable
  BCTRL.DRVH: BmaxVariable
  BACT: QuadrupoleBACTVariable
  BDES: QuadrupoleBCTRLVariable
  BMAX: BmaxVariable
  BMIN: BminVariable
  STATCTRLSUB.T: StatusVariable
  CTRL: ControlStateVariable

Solenoid:
  BCTRL: SolenoidBCTRLVariable
  BCTRL.DRVL: BminVariable
  BCTRL.DRVH: BmaxVariable
  BACT: SolenoidBACTVariable
  BDES: SolenoidBCTRLVariable
  BMIN: BminVariable
  BMAX: BmaxVariable
  STATCTRLSUB.T: StatusVariable
  CTRL: ControlStateVariable

HorizontalCorrector:
  BCTRL: KickerBCTRLVariable
  BCTRL.DRVL: BminVariable
  BCTRL.DRVH: BmaxVariable
  BACT: KickerBACTVariable
  BDES: KickerBCTRLVariable
  BMIN: BminVariable
  BMAX: BmaxVariable
  STATCTRLSUB.T: StatusVariable
  CTRL: ControlStateVariable

VerticalCorrector:
  BCTRL: KickerBCTRLVariable
  BCTRL.DRVL: BminVariable
  BCTRL.DRVH: BmaxVariable
  BACT: KickerBACTVariable
  BDES: KickerBCTRLVariable
  BMIN: BminVariable
  BMAX: BmaxVariable
  STATCTRLSUB.T: StatusVariable
  CTRL: ControlStateVariable

Klystron:
  ENLD: KlystronENLDVariable # subclass of BmadScalarVariable
  PACT: KlystronPACTVariable # subclass of BmadScalarVariable
  PDES: KlystronPDESVariable # subclass of BmadScalarVariable
  BEAMCODE1_STAT: KlystronStatVariable # subclass of BmadEnumVariable
  BEAMCODE2_STAT: KlystronStatVariable # subclass of BmadEnumVariable
  # SWRD: KlystronSWRDVariable # subclass of BmadIntVariable
  # STAT: KlystronSTATVariable # subclass of BmadIntVariable
  # HDSC: KlystronHDSCVariable # subclass of BmadIntVariable
  # DSTA: KlystronDSTAVariable # subclass of NDVariable
