BPM:
  X: BPMXVariable
  Y: BPMYVariable

Quadrupole:
  BCTRL: QuadrupoleBCTRLVariable
  BCTRL.DRVL: BminVariable
  BCTRL.DRVH: BmaxVariable
  BACT: QuadrupoleBACTVariable
  BDES: QuadrupoleBCTRLVariable
  BMAX: BmaxVariable
  BMIN: BminVariable
  STATCTRLSUB.T: StatusVariable
  CTRL: ControlStateVariable

Solenoid:
  BCTRL: SolenoidBCTRLVariable
  BCTRL.DRVL: BminVariable
  BCTRL.DRVH: BmaxVariable
  BACT: SolenoidBACTVariable
  BDES: SolenoidBCTRLVariable
  BMIN: BminVariable
  BMAX: BmaxVariable
  STATCTRLSUB.T: StatusVariable
  CTRL: ControlStateVariable

HorizontalCorrector:
  BCTRL: KickerBCTRLVariable
  BCTRL.DRVL: BminVariable
  BCTRL.DRVH: BmaxVariable
  BACT: KickerBACTVariable
  BDES: KickerBCTRLVariable
  BMIN: BminVariable
  BMAX: BmaxVariable
  STATCTRLSUB.T: StatusVariable
  CTRL: ControlStateVariable

VerticalCorrector:
  BCTRL: KickerBCTRLVariable
  BCTRL.DRVL: BminVariable
  BCTRL.DRVH: BmaxVariable
  BACT: KickerBACTVariable
  BDES: KickerBCTRLVariable
  BMIN: BminVariable
  BMAX: BmaxVariable
  STATCTRLSUB.T: StatusVariable
  CTRL: ControlStateVariable
