SLAC_VARIABLE_CONFIG:

  BPM:
    X:
      unit: mm
      read_only: true
      variable_class: lume.variables.ScalarVariable
    Y:
      unit: mm
      read_only: true
      variable_class: lume.variables.ScalarVariable

  QUAD:
    BCTRL:
      unit: kG
      read_only: false
      variable_class: lume.variables.ScalarVariable
    BACT:
      unit: kG
      read_only: true
      variable_class: lume.variables.ScalarVariable
    BMIN:
      unit: kG
      read_only: true
      variable_class: lume.variables.ScalarVariable
    BMAX:
      unit: kG
      read_only: true
      variable_class: lume.variables.ScalarVariable

  XCOR:
    BCTRL:
      unit: kG-m
      read_only: false
      variable_class: lume.variables.ScalarVariable
    BACT:
      unit: kG-m
      read_only: true
      variable_class: lume.variables.ScalarVariable
    BMIN:
      unit: kG-m
      read_only: true
      variable_class: lume.variables.ScalarVariable
    BMAX:
      unit: kG-m
      read_only: true
      variable_class: lume.variables.ScalarVariable

  YCOR:
    BCTRL:
      unit: kG-m
      read_only: false
      variable_class: lume.variables.ScalarVariable
    BACT:
      unit: kG-m
      read_only: true
      variable_class: lume.variables.ScalarVariable
    BMIN:
      unit: kG-m
      read_only: true
      variable_class: lume.variables.ScalarVariable
    BMAX:
      unit: kG-m
      read_only: true
      variable_class: lume.variables.ScalarVariable

  OTRS:
    Image:ArrayData:
      unit: pixel
      read_only: true
      variable_class: lume.variables.NDVariable
    PNEUMATIC:
      unit: bool
      read_only: false
      variable_class: lume.variables.ScalarVariables
    Image:ArraySize1_RBV:
      unit: pixel
      read_only: false
      variable_class: lume.variables.ScalarVariables
    Image:ArraySize0_RBV:
      unit: pixel
      read_only: false
      variable_class: lume.variables.ScalarVariables  
    RESOLUTION:
      unit: pixel/mm
      read_only: true
      variable_class: lume.variables.ScalarVariable
    IMAGE:
      unit: pixel
      read_only: true
      variable_class: lume.variables.NDVariable
    N_OF_ROW:
      unit: pixel
      read_only: false
      variable_class: lume.variables.ScalarVariable
    N_OF_COL: 
      unit: pixel
      read_only: false
      variable_class: lume.variables.ScalarVariable