name: Run tests

on:
  pull_request:
  push:
  release:
    types:
      - published

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12", "3.13"]
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - name: Free disk space
        run: |
          df -h
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/CodeQL
          sudo docker image prune --all --force
          df -h
      - uses: actions/checkout@4f1f4aec02e41874fa0262ea8ff5172d7978ad1e
        with:
          fetch-depth: 1
      - name: Checkout lcls-lattice
        uses: actions/checkout@4f1f4aec02e41874fa0262ea8ff5172d7978ad1e
        with:
          repository: slaclab/lcls-lattice
          # temp change branch to address bmad bug TODO: should remove when bug is resolved
          ref: temp_remove_fixers
          path: lcls-lattice
      - name: Checkout facet2-lattice
        uses: actions/checkout@4f1f4aec02e41874fa0262ea8ff5172d7978ad1e
        with:
          repository: slaclab/facet2-lattice
          path: facet2-lattice
          ref: b1d170ebf51582c1dc675595d810f5191866a443
      - name: Set up conda environment
        uses: conda-incubator/setup-miniconda@6bd9d14c76e9fc5223db3dd28e004f2c458599e8
        with:
          miniforge-version: latest
          python-version: ${{ matrix.python-version }}
          channels: conda-forge
          channel-priority: strict
          activate-environment: va-env
      - name: Install pytao (includes bmad)
        run: conda install -y pytao
      - name: Install CPU-only PyTorch
        run: pip install --upgrade --index-url https://download.pytorch.org/whl/cpu torch
      - name: Install package and remaining dependencies
        run: pip install ".[all,dev]"
      - name: List Python package versions
        run: pip list
      - name: Run tests
        env:
          LCLS_LATTICE: ${{ github.workspace }}/lcls-lattice
          FACET2_LATTICE: ${{ github.workspace }}/facet2-lattice
        run: pytest virtual_accelerator/tests -v --tb=short -ra --strict-markers
